name: CI Joomla

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  code-style-php:
    name: Check PHP code style
    runs-on: ubuntu-latest
    container: joomlaprojects/docker-images:php8.5
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Check PHP code style
        env:
          PHP_CS_FIXER_IGNORE_ENV: true
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          composer config --global home
          composer validate --no-check-all --strict
          composer install --no-progress --ignore-platform-reqs
          ./libraries/vendor/bin/php-cs-fixer fix -vvv --diff
