name: CI Joomla

on:
  push:
  pull_request:

jobs:
  composer:
    name: Install PHP dependencies
    runs-on: ubuntu-latest
    container: joomlaprojects/docker-images:php8.4
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        id: cache-php
        with:
          path: libraries/vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        id: cache-webauthn
        with:
          path: plugins/system/webauthn/fido.jwt
          key: ${{ runner.os }}-webauthn-${{ hashFiles('composer.lock') }}
      - name: Install PHP dependencies
        if: steps.cache-php.outputs.cache-hit != 'true'
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          composer config --global home
          composer validate --no-check-all --strict
          composer install --no-progress --ignore-platform-reqs

  npm:
    name: Install JS/CSS dependencies and build assets
    runs-on: ubuntu-latest
    container: joomlaprojects/docker-images:php8.4
    needs: [composer]
    steps:
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: latest
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        id: cache-assets
        with:
          path: |
            node_modules
            media
            installation/template/css
            installation/template/images
            installation/template/js
            installation/template/scss
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json', 'build/build.mjs', 'build/build-modules-js/**', 'media_source/**') }}
      - uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: libraries/vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
      - uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: plugins/system/webauthn/fido.jwt
          key: ${{ runner.os }}-webauthn-${{ hashFiles('composer.lock') }}
      - name: Build assets
        if: steps.cache-assets.outputs.cache-hit != 'true'
        run: npm ci

  tests-system-prepare:
    name: Prepare system tests
    runs-on: ubuntu-latest
    container: joomlaprojects/docker-images:cypress8.4
    needs: [composer, npm]
    env:
      CYPRESS_VERIFY_TIMEOUT: 100000
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            node_modules
            media
            installation/template/css
            installation/template/images
            installation/template/js
            installation/template/scss
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json', 'build/build.mjs', 'build/build-modules-js/**', 'media_source/**') }}
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        id: cache-cypress
        with:
          path: |
            /root/.cache/Cypress
            /github/home/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('package-lock.json') }}
      - name: Install Cypress dependencies
        if: steps.cache-cypress.outputs.cache-hit != 'true'
        run: |
          npx cypress install
          npx cypress verify

  tests-system:
    name: Run system tests
    runs-on: ubuntu-latest
    container: joomlaprojects/docker-images:cypress${{ matrix.config.php_version }}
    needs: [tests-system-prepare]
    strategy:
      matrix:
        config:
          - php_version: '8.5'
            test_group: cmysql
            db_engine: mysqli
            db_host: mysql
            my_version: '9'
            browser: 'chrome'
          - php_version: '8.3'
            test_group: cpostgres
            db_engine: pgsql
            db_host: postgres
            pg_version: '18.0'
            browser: 'edge'
    env:
      JOOMLA_INSTALLATION_DISABLE_LOCALHOST_CHECK: 1
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: libraries/vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
      - uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: plugins/system/webauthn/fido.jwt
          key: ${{ runner.os }}-webauthn-${{ hashFiles('composer.lock') }}
      - uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            node_modules
            media
            installation/template/css
            installation/template/images
            installation/template/js
            installation/template/scss
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json', 'build/build.mjs', 'build/build-modules-js/**', 'media_source/**') }}
      - uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            /root/.cache/Cypress
            /github/home/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('package-lock.json') }}
      - name: Run System tests
        run: bash tests/System/entrypoint.sh "$(pwd)" ${{ matrix.config.test_group }} ${{ matrix.config.db_engine }} ${{ matrix.config.db_host }} ${{ matrix.config.browser }}
      - name: Archive test results results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: always()
        with:
          name: system-test-output
          path: tests/System/output
          if-no-files-found: ignore
    services:
      mysql:
        image: mysql:${{ matrix.config.my_version || '9' }}
        env:
          MYSQL_USER: joomla_ut
          MYSQL_PASSWORD: joomla_ut
          MYSQL_ROOT_PASSWORD: joomla_ut
          MYSQL_DATABASE: test_joomla
      postgres:
        image: postgres:${{ matrix.config.pg_version || '18' }}-alpine
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: joomla_ut
          POSTGRES_DB: test_joomla
